# Generated by Django 5.0.7 on 2024-09-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
