# Generated by Django 5.0.7 on 2024-09-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0007_desserts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="desserts",
            new_name="dessert",
        ),
    ]
